# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fit Kid  use pod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fit Kid  use pod

  target 'Fit Kid  use podTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'Fit Kid  use podUITests' do
    # Pods for testing
  end

end
